server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
        - id: product-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/products/**