# Versão da sintaxe do Docker Compose
version: '3.8'

# Bloco onde declaramos todos os nossos serviços (contêineres)
services:

  # Serviço para o PostgreSQL
  postgres-db:
    image: postgres:16 # Usamos uma versão específica em vez de 'latest'
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Serviço para o MongoDB
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Serviço para o Redis
  redis-db:
    image: redis:latest
    container_name: redis-db
    command: --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce-network
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  ecommerce-network:
    driver: bridge
