server:
  port: 8083

spring:
  application:
    name: product-catalog-service
  data:
    mongodb:
      # Formato: mongodb://<user>:<password>@<host>:<port>/<database>?authSource=admin
      uri: mongodb://admin:admin@localhost:27017/product_catalog_db?authSource=admin